environment: production 
chdir: /home/kirel/detexify/current
address: 0.0.0.0 
user: kirel 
group: kirel 
port: 7654
pid: tmp/pids/thin.pid 
rackup: config.ru 
log: log/thin.log 
max_conns: 1024 
timeout: 30 
max_persistent_conns: 512 
daemonize: true
servers: 1